### ISSUE TITLE
[device-report] Royal kludge RK G68

### ISSUE THREAD

**Issue by Chumet** [carlossless/sinowealth-kb-tool#70]
## Device Info

- Sinowealth Device: `SH68F90A`
- IC Label:  `BYK916`
- Product Page: http://en.rkgaming.com/product/13/

## Part Info

```
firmware_size: 61440
vendor_id: 0x258a
product_id: 0x0049
bootloader_size: 4096 # necessary if not default, otherwise remove this line
page_size: 2048 # necessary if not default, otherwise remove this line
isp_usage_page: 0xff00 # necessary if not default, otherwise remove this line
isp_usage: 0x0001 # necessary if not default, otherwise remove this line
isp_index: 0 # necessary if not default, otherwise remove this line
```

## Operations Tested

- [x] Read
- [ ] Write

## Platforms Tested

- [ ] linux
- [ ] macos
- [x] windows

## Checksums

- Bootloader MD5: `cfc8661da8c9d7e351b36c0a763426aa`
- Stock Firmware MD5: `9dc83b7be7eefd21418c20a129525e3e` without ISP

## HID Dump

A dump from [usbhid-dump](https://github.com/DIGImend/usbhid-dump), [win-hid-dump](https://github.com/todbot/win-hid-dump) or [mac-hid-dump](https://github.com/todbot/mac-hid-dump)

<details>
<summary>HID Tool Output</summary>

```
# Royal Kludge RK G68 using win-hid-dump
...
258A:0049: SINO WEALTH -
PATH:\\?\hid#vid_258a&pid_0049&mi_01&col03#8&269fe19f&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
DESCRIPTOR:
  06  00  FF  09  01  A1  01  85  05  15  00  25  01  35  00  45
  01  65  00  55  00  75  01  95  28  B1  03  C1  00
  (29 bytes)
258A:0049: SINO WEALTH - RK Bluetooth Keyboard
PATH:\\?\hid#vid_258a&pid_0049&mi_01&col05#8&269fe19f&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
DESCRIPTOR:
  06  00  FF  09  01  A1  01  85  0A  09  00  15  00  25  FF  35
  00  45  00  65  00  55  00  75  08  95  40  B1  02  C1  00
  (31 bytes)
...
```

</details>

## Questions
@carlossless, I have been able to read without problems, now I want to flash the VIA firmware, there is one called rkg68_via.hex here: https://www.caniusevia.com/docs/download_firmware, I can use sinowealth-kb-tool to write this firmware? Do you think I can leave it like a brick? I would like to be able to use the entire VIA or QMK environment. But seeing that there are so many variants of Royal Kludge (68) I don't know if the firmware offered on the VIA website is suitable for my keyboard. Mine is RGB, ANSI layout with Bluetooth, 2.4Ghz and USB-C, in addition to having 2 USB ports. There is another version of this keyboard, the RK68 that does not have those 2 extra USB ports.

![IMG_20240413_193610](https://github.com/carlossless/sinowealth-kb-tool/assets/161529849/1ae4c487-bd83-441e-8c18-2ac9353d3409)
![IMG_20240413_193618](https://github.com/carlossless/sinowealth-kb-tool/assets/161529849/c3291684-d6e8-4c5f-9ea9-f33a183d3097)
![IMG_20240415_011555](https://github.com/carlossless/sinowealth-kb-tool/assets/161529849/d37800ba-ff6f-4bd0-8598-65df579e8af3)

**Comment by carlossless** [comment]
@Chumet thanks for the report! Especially for those PCB pictures. I should make this part of the issue template so that more people are encouraged to provide them :)

> I have been able to read without problems, now I want to flash the VIA firmware, there is one called rkg68_via.hex here: https://www.caniusevia.com/docs/download_firmware, I can use sinowealth-kb-tool to write this firmware? Do you think I can leave it like a brick? I would like to be able to use the entire VIA or QMK environment

QMK (with VIA) will most certainly not work as it's [designed specifically for ARM and AVR architectures](https://github.com/qmk/qmk_firmware/blob/master/docs/compatible_microcontrollers.md) and the SH68F90A is an [8051](https://en.wikipedia.org/wiki/MCS-51) based microcontroller.

8051 isn't supported by mainstream compilers like gcc or llvm, and the most popular oss compiler that does support it is [sdcc](https://sdcc.sourceforge.net/), but it lacks many features that QMKs code relies on, making porting it non-trivial (among other issues).

If you're interested in developing firmware for keyboards like this one, you might want to check out: [smk](https://github.com/carlossless/smk), but be warned that it's still in experimental/pre-alpha stage, I don't recommend it for general usage and it is provided as-is with no additional support.
